const recipes = RECIPES.filter(r => !r.draft);
let selectedCategory="Alle";
let saved=savedRecipes();
const grid=document.querySelector("#recipeGrid"),empty=document.querySelector("#emptyState"),search=document.querySelector("#search"),dialog=document.querySelector("#savedDialog"),recipeDialog=document.querySelector("#recipeDialog");
const ranking=[{id:1,saves:"2.4k"},{id:3,saves:"1.9k"},{id:2,saves:"1.6k"},{id:5,saves:"1.2k"},{id:6,saves:"980"}];document.querySelector("#rankingList").innerHTML=ranking.map((item,index)=>{const recipe=recipes.find(r=>r.id===item.id);return `<li><span class="rank-number">${index+1}</span><span class="rank-emoji ${recipe.color}">${recipe.emoji}</span><span><strong>${recipe.title}</strong><small>${recipe.category}</small></span><b>♡ ${item.saves}</b></li>`}).join("");
function renderRecipes(){const q=search.value;const visible=q.trim()?searchRecipes(RECIPES,q):recipes;grid.innerHTML=visible.map(r=>`<article class="recipe-card" data-recipe-id="${r.id}" tabindex="0" role="button" aria-label="Rezept ${r.title} öffnen"><div class="recipe-image ${r.color}"><span class="recipe-emoji">${r.emoji}</span><button class="heart ${saved.includes(r.id)?"is-saved":""}" data-id="${r.id}" aria-label="${r.title} speichern">${saved.includes(r.id)?"♥":"♡"}</button><span class="tag">${r.category}</span></div><div class="recipe-content"><h3>${r.title}</h3><span>${r.note}</span>${infoPills(r)}<button class="recipe-open" data-open-id="${r.id}">Rezept ansehen <b>→</b></button></div></article>`).join("");empty.hidden=visible.length>0;document.querySelector("#savedCount").textContent=saved.length}
function openRecipe(id){const r=RECIPES.find(item=>item.id===id);document.querySelector("#recipeDetail").innerHTML=recipeDetailHTML(r);recipeDialog.showModal()}
search.addEventListener("input",renderRecipes);grid.addEventListener("click",e=>{const heart=e.target.closest(".heart");if(heart){const id=Number(heart.dataset.id);saved=toggleSaved(id);renderRecipes();return}const open=e.target.closest("[data-open-id]");if(open){e.stopPropagation();openRecipe(Number(open.dataset.openId));return}const card=e.target.closest("[data-recipe-id]");if(card)openRecipe(Number(card.dataset.recipeId))});
grid.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){const card=e.target.closest("[data-recipe-id]");if(card){e.preventDefault();openRecipe(Number(card.dataset.recipeId))}}});
document.querySelector("#savedButton").addEventListener("click",()=>{const list=RECIPES.filter(r=>saved.includes(r.id));document.querySelector("#savedList").innerHTML=list.length?list.map(r=>`<div class="saved-row"><span>${r.emoji}</span><div><strong>${r.title}</strong><small>${r.note}</small></div></div>`).join(""):"<p class='empty-saved'>Deine Rezept-Sammlung wartet auf ihren ersten Favoriten.</p>";dialog.showModal()});
document.querySelector("#closeDialog").addEventListener("click",()=>dialog.close());document.querySelector("#closeRecipeDialog").addEventListener("click",()=>recipeDialog.close());document.querySelector("#newsletterForm").addEventListener("submit",e=>{e.preventDefault();document.querySelector("#newsletterMessage").textContent="Danke – du bist auf der Matchly-Liste!";e.target.reset()});renderRecipes();
