const recipes = RECIPES.filter(r => !r.draft);
let selectedCategory="Alle";
let saved=savedRecipes();
const grid=document.querySelector("#recipeGrid"),empty=document.querySelector("#emptyState"),search=document.querySelector("#search"),dialog=document.querySelector("#savedDialog"),recipeDialog=document.querySelector("#recipeDialog"),popularGrid=document.querySelector("#popularGrid");
const ranking=[{id:1,saves:"2.4k"},{id:3,saves:"1.9k"},{id:2,saves:"1.6k"},{id:5,saves:"1.2k"},{id:6,saves:"980"}];document.querySelector("#rankingList").innerHTML=ranking.map((item,index)=>{const recipe=recipes.find(r=>r.id===item.id);return `<li><span class="rank-number">${index+1}</span><span class="rank-emoji ${recipe.color}">${recipe.emoji}</span><span><strong>${recipe.title}</strong><small>${recipe.category}</small></span><b>♡ ${item.saves}</b></li>`}).join("");
const fmtSaves=n=>n>=1000?(n/1000).toFixed(1).replace(/\.0$/,"")+"k":String(n);
function cardHTML(r,noBadge){const badge=r.popular&&!noBadge?`<span class="popular-badge">🔥 Beliebt diese Woche</span>`:"";const community=r.rating?`<div class="community-row"><span class="rating">★ ${r.rating.toFixed(1)}</span><span>${r.reviews} Bewertungen</span><span>♡ ${fmtSaves(r.saves)} gespeichert</span></div>`:"";return `<article class="recipe-card" data-recipe-id="${r.id}" tabindex="0" role="button" aria-label="Rezept ${r.title} öffnen"><div class="recipe-image ${r.color}"><span class="recipe-emoji">${r.emoji}</span><button class="heart ${saved.includes(r.id)?"is-saved":""}" data-id="${r.id}" aria-label="${r.title} speichern">${saved.includes(r.id)?"♥":"♡"}</button>${badge}<span class="tag">${r.category}</span></div><div class="recipe-content"><h3>${r.title}</h3><span>${r.note}</span>${infoPills(r)}${community}<button class="recipe-open" data-open-id="${r.id}">Rezept ansehen <b>→</b></button></div></article>`}
function renderRecipes(){const q=search.value;const visible=q.trim()?searchRecipes(RECIPES,q):recipes;grid.innerHTML=visible.map(r=>cardHTML(r)).join("");empty.hidden=visible.length>0;document.querySelector("#savedCount").textContent=saved.length}
function renderPopular(){const popular=RECIPES.filter(r=>r.popular).sort((a,b)=>b.saves-a.saves).slice(0,3);popularGrid.innerHTML=popular.map(r=>cardHTML(r,true)).join("")}
function openRecipe(id){const r=RECIPES.find(item=>item.id===id);document.querySelector("#recipeDetail").innerHTML=recipeDetailHTML(r);recipeDialog.showModal()}
function bindGrid(target){target.addEventListener("click",e=>{const heart=e.target.closest(".heart");if(heart){saved=toggleSaved(Number(heart.dataset.id));renderRecipes();renderPopular();return}const open=e.target.closest("[data-open-id]");if(open){e.stopPropagation();openRecipe(Number(open.dataset.openId));return}const card=e.target.closest("[data-recipe-id]");if(card)openRecipe(Number(card.dataset.recipeId))});target.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){const card=e.target.closest("[data-recipe-id]");if(card){e.preventDefault();openRecipe(Number(card.dataset.recipeId))}}})}
search.addEventListener("input",renderRecipes);bindGrid(grid);bindGrid(popularGrid);
document.querySelector("#recipeDetail").addEventListener("click",e=>{const heart=e.target.closest(".detail-heart");if(heart){const id=Number(heart.dataset.id);saved=toggleSaved(id);heart.classList.toggle("is-saved",saved.includes(id));heart.textContent=saved.includes(id)?"♥":"♡";document.querySelector("#savedCount").textContent=saved.length;return}const share=e.target.closest(".detail-share");if(share){const r=RECIPES.find(x=>x.id===Number(share.dataset.shareId));if(r)shareRecipe(r);return}const similar=e.target.closest("[data-detail-open]");if(similar)openRecipe(Number(similar.dataset.detailOpen))});
document.querySelector("#savedButton").addEventListener("click",()=>{const list=RECIPES.filter(r=>saved.includes(r.id));document.querySelector("#savedList").innerHTML=list.length?list.map(r=>`<div class="saved-row"><span>${r.emoji}</span><div><strong>${r.title}</strong><small>${r.note}</small></div></div>`).join(""):"<p class='empty-saved'>Deine Rezept-Sammlung wartet auf ihren ersten Favoriten.</p>";dialog.showModal()});
document.querySelector("#closeDialog").addEventListener("click",()=>dialog.close());document.querySelector("#closeRecipeDialog").addEventListener("click",()=>recipeDialog.close());document.querySelector("#newsletterForm").addEventListener("submit",e=>{e.preventDefault();document.querySelector("#newsletterMessage").textContent="Danke – du bist auf der Matchly-Liste!";e.target.reset()});renderRecipes();renderPopular();
