const category=new URLSearchParams(location.search).get("category")||"Alle";
const info={Alle:["Alle Rezepte","Entdecke alle kleinen Matcha-Momente an einem Ort."],Iced:["Iced & Fresh","Zehn eisgekühlte Matcha-Rezepte für sonnige Tage und frische Pausen."],Cremig:["Cremig & Sweet","Elf samtige Matcha-Kreationen für deinen gemütlichen Genussmoment."],Fruchtig:["Fruchtig","Zehn leichte, frische Matcha-Rezepte mit deinen Lieblingsfrüchten."],Wellness:["Wellness","Zehn bewusste Matcha-Momente, die einfach gut schmecken."]}[category]||["Alle Rezepte","Matcha-Inspiration für dich."];
document.title=category==="Alle"?"Matchly Kategorien":`${info[0]} — Matchly`;document.querySelector("#categoryTitle").textContent=info[0];document.querySelector("#categoryIntro").textContent=info[1];
for(const c of ["Alle","Iced","Cremig","Fruchtig","Wellness"]){document.querySelector(`#pill-${c}`).classList.toggle("active",c===category)}
const categoryRecipes=category==="Alle"?RECIPES:RECIPES.filter(r=>r.category===category);
let saved=savedRecipes();
const grid=document.querySelector("#categoryRecipeGrid"),modal=document.querySelector("#categoryRecipeDialog"),categorySearch=document.querySelector("#categorySearch"),emptyEl=document.querySelector("#categoryEmptyState");
function cardHTML(r){return `<article class="recipe-card" data-recipe-id="${r.id}" tabindex="0" role="button" aria-label="${r.title} öffnen"><div class="recipe-image ${r.color}"><span class="recipe-emoji">${r.emoji}</span><button class="heart ${saved.includes(r.id)?"is-saved":""}" data-id="${r.id}" aria-label="${r.title} speichern">${saved.includes(r.id)?"♥":"♡"}</button><span class="tag">${r.category}</span></div><div class="recipe-content"><h3>${r.title}</h3><span>${r.note}</span>${infoPills(r)}<button class="recipe-open" data-recipe-id="${r.id}">Rezept ansehen <b>→</b></button></div></article>`}
function renderCategory(){const q=categorySearch.value;const visible=q.trim()?searchRecipes(categoryRecipes,q):categoryRecipes;grid.innerHTML=visible.map(cardHTML).join("");emptyEl.hidden=visible.length>0}
function openCategoryRecipe(id){const r=RECIPES.find(item=>item.id===id);document.querySelector("#categoryRecipeDetail").innerHTML=recipeDetailHTML(r);modal.showModal()}
categorySearch.addEventListener("input",renderCategory);
grid.addEventListener("click",e=>{const heart=e.target.closest(".heart");if(heart){saved=toggleSaved(Number(heart.dataset.id));renderCategory();return}const card=e.target.closest("[data-recipe-id]");if(card)openCategoryRecipe(Number(card.dataset.recipeId))});
grid.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){const card=e.target.closest("[data-recipe-id]");if(card){e.preventDefault();openCategoryRecipe(Number(card.dataset.recipeId))}}});
document.querySelector("#closeCategoryRecipe").addEventListener("click",()=>modal.close());
document.querySelector("#categoryRecipeDetail").addEventListener("click",e=>{const heart=e.target.closest(".detail-heart");if(heart){const id=Number(heart.dataset.id);saved=toggleSaved(id);heart.classList.toggle("is-saved",saved.includes(id));heart.textContent=saved.includes(id)?"♥":"♡";return}const check=e.target.closest("input[data-check-idx]");if(check){toggleChecked(Number(check.dataset.recipeId),Number(check.dataset.checkIdx));check.closest(".check-item").classList.toggle("is-checked",check.checked);return}const step=e.target.closest("input[data-step-idx]");if(step){toggleStep(Number(step.dataset.recipeId),Number(step.dataset.stepIdx));const item=step.closest(".step-item");if(item)item.classList.toggle("is-checked",step.checked);const ol=step.closest("ol");if(ol){const small=ol.closest("section").querySelector("h3 small");if(small)small.textContent=`${ol.querySelectorAll(".step-item.is-checked").length}/${ol.querySelectorAll(".step-item").length} Schritte`}return}const share=e.target.closest(".detail-share");if(share){const r=RECIPES.find(x=>x.id===Number(share.dataset.recipeId));if(r)shareRecipe(r);return}const star=e.target.closest(".rating-star");if(star){setRating(Number(star.dataset.recipeId),Number(star.dataset.rating));document.querySelector("#categoryRecipeDetail").innerHTML=recipeDetailHTML(RECIPES.find(x=>x.id===Number(star.dataset.recipeId)));return}const similar=e.target.closest("[data-detail-open]");if(similar)openCategoryRecipe(Number(similar.dataset.detailOpen))});
document.querySelector("#categoryRanking").innerHTML=categoryRecipes.slice(0,5).map((recipe,index)=>`<li><b>${index+1}</b><strong>${recipe.title}</strong><span>♡ ${(14-index*2)}${index===0?"2":"8"}</span></li>`).join("");
renderCategory();
