const RECIPES = [
  {id:1,title:"Strawberry Cloud Matcha",category:"Fruchtig",time:"8 Min.",level:"Einfach",color:"berry",emoji:"🍓",note:"Erdbeere · Vanille · Hafermilch",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan möglich","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","4 reife Erdbeeren","1 TL Ahornsirup","180 ml Hafermilch","1/2 TL Vanilleextrakt","Eiswürfel"],steps:["Erdbeeren mit Ahornsirup fein pürieren und in ein hohes Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eiswürfel auf das Erdbeerpüree geben. Hafermilch mit Vanille darauf gießen.","Matcha langsam über die Milch gießen und vor dem Trinken umrühren."],description:"Luftig-süße Erdbeerwolke auf cremigem Matcha – ein fruchtiger Iced Latte für den kleinen Genussmoment zwischendurch.",image:"images/recipes/strawberry-cloud-matcha.jpg",rating:4.9,reviews:312,saves:2400,popular:true,servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:2,title:"Coconut Iced Matcha",category:"Iced",time:"5 Min.",level:"Einfach",color:"coconut",emoji:"🥥",note:"Kokos · Limette · zeremonieller Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","160 ml Kokosdrink","40 ml Kokosmilch","1 TL Agavendicksaft","1 Spritzer Limettensaft","Eiswürfel"],steps:["Matcha sieben und mit heißem Wasser glatt und schaumig rühren.","Kokosdrink, Kokosmilch, Agavendicksaft und Limettensaft verrühren.","Ein Glas mit Eiswürfeln füllen und die Kokosmischung hineingießen.","Matcha darübergeben. Für den Farbverlauf nicht sofort umrühren."],description:"Kokos, Limette und zeremonieller Matcha – eiskalt und samtig, wie ein Mini-Urlaub im Glas.",image:"images/recipes/coconut-iced-matcha.jpg",rating:4.8,reviews:240,saves:1600,popular:true,servings:"1 Glas",allergens:["Kokos"],draft:false},
  {id:3,title:"Vanilla Cream Matcha",category:"Cremig",time:"7 Min.",level:"Einfach",color:"vanilla",emoji:"☁",note:"Vanille · Matcha · Cream Foam",sweet:"Süß",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","180 ml Milch oder Hafermilch","2 EL Sahne oder vegane Schlagcreme","1 TL Vanillesirup","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser anrühren und aufschlagen.","Sahne mit Vanillesirup kurz cremig, aber noch gießbar aufschlagen.","Ein Glas mit Eis und Milch füllen. Den Matcha langsam hineingießen.","Zum Schluss die Vanille-Cream obenauf geben."],description:"Samtige Vanille-Creme auf sattem Matcha: der süße Klassiker für alle, die es cremig und gemütlich mögen.",image:"images/recipes/vanilla-cream-matcha.jpg",rating:4.8,reviews:268,saves:1900,popular:true,servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:4,title:"Blueberry Oat Matcha",category:"Fruchtig",time:"10 Min.",level:"Mittel",color:"blueberry",emoji:"🫐",note:"Blaubeere · Hafer · Ahorn",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","70 g Blaubeeren","1 TL Ahornsirup","1 TL Zitronensaft","180 ml Hafermilch","Eiswürfel"],steps:["Blaubeeren, Ahornsirup und Zitronensaft pürieren.","Matcha mit heißem Wasser schaumig schlagen.","Blaubeerpüree in ein Glas geben und mit Eis auffüllen.","Hafermilch und danach den Matcha vorsichtig eingießen."],description:"Beerige Blaubeeren, Hafer und ein Hauch Ahorn – ein wohliges Wellness-Getränk mit natürlicher Süße.",image:"images/recipes/blueberry-oat-matcha.jpg",rating:4.5,reviews:97,saves:640,popular:false,servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:5,title:"Peachy Matcha Tonic",category:"Fruchtig",time:"6 Min.",level:"Einfach",color:"peach",emoji:"🍑",note:"Pfirsich · Tonic · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Erfrischend"],ingredients:["1 TL Matcha-Pulver","50 ml heißes Wasser (ca. 80 °C)","1/2 reifer Pfirsich","1 TL Honig oder Agavendicksaft","120 ml mildes Tonic Water","Eiswürfel"],steps:["Pfirsich mit Honig oder Agavendicksaft fein pürieren und in ein Glas füllen.","Das Glas mit Eiswürfeln auffüllen und Tonic Water langsam dazugießen.","Matcha sieben, mit heißem Wasser glatt rühren und behutsam über einen Löffel auf das Getränk gießen.","Mit einer Pfirsichscheibe garnieren."],description:"Spritzig-leichter Pfirsich-Tonic mit Matcha: prickelnd und erfrischend – perfekt für sonnige Nachmittage.",image:"images/recipes/peachy-matcha-tonic.jpg",rating:4.7,reviews:158,saves:1200,popular:true,servings:"1 Glas",allergens:["Honig (optional)"],draft:false},
  {id:6,title:"Pistachio Latte",category:"Cremig",time:"8 Min.",level:"Mittel",color:"pistachio",emoji:"◒",note:"Pistazie · Mandel · Matcha",sweet:"Mittel",temperature:"Heiß oder kalt",vegan:"Ja",tags:["Vegan möglich","Kalt oder warm"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","200 ml Mandeldrink","1 EL Pistazienmus","1 TL Ahornsirup","1 Prise Salz","Eiswürfel für die kalte Variante"],steps:["Pistazienmus, Ahornsirup und Salz mit einem Schluck Mandeldrink glatt rühren.","Restlichen Mandeldrink dazugeben und kalt mit Eis servieren oder aufschäumen.","Matcha sieben und mit heißem Wasser schaumig schlagen.","Matcha auf die Pistazienmilch gießen und nach Wunsch mit Pistazien dekorieren."],description:"Pistazienmus trifft Matcha: nussig, samtig und doppelt grün – kalt oder warm ein Genuss.",image:"images/recipes/pistachio-latte.jpg",rating:4.7,reviews:132,saves:980,popular:true,servings:"1 Glas",allergens:["Nüsse (Mandel, Pistazie)"],draft:false},
  {id:7,title:"Classic Iced Oat Matcha",category:"Iced",time:"5 Min.",level:"Einfach",color:"coconut",emoji:"❋",note:"Haferdrink · Eis · zeremonieller Matcha",sweet:"Wenig",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","200 ml Haferdrink","1 TL Ahornsirup (optional)","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eiswürfeln füllen und den Haferdrink hineingießen.","Matcha langsam über den Haferdrink gießen.","Kurz umrühren und sofort servieren."],description:"Der zeitlose Klassiker: zeremonieller Matcha auf cremigem Haferdrink – pur, grün und einfach gut.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:8,title:"Vanilla Iced Matcha",category:"Iced",time:"5 Min.",level:"Einfach",color:"vanilla",emoji:"☁",note:"Vanille · Milch · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","180 ml Milch","1/2 TL Vanilleextrakt","1 TL Ahornsirup","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Milch mit Vanilleextrakt und Ahornsirup verrühren.","Ein Glas mit Eis füllen und die Vanillemilch hineingießen.","Matcha darübergeben, vorsichtig umrühren und servieren."],description:"Sahnige Milch mit Vanille, eiskalt serviert mit sattem Matcha – der sanfte Alltagsgenuss.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:9,title:"Salted Maple Matcha",category:"Iced",time:"6 Min.",level:"Einfach",color:"pistachio",emoji:"✦",note:"Ahorn · Meersalz · Hafer",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","200 ml Haferdrink","1 EL Ahornsirup","1 Prise Meersalz","Eiswürfel"],steps:["Ahornsirup und Meersalz mit dem Haferdrink glatt rühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Ahorn-Hafermilch hineingießen.","Matcha langsam dazugeben, kurz umrühren und servieren."],description:"Süßer Ahorn trifft eine Prise Meersalz – ein eiskalter Matcha mit süß-salzigem Twist.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:10,title:"Strawberry Cold Foam Matcha",category:"Iced",time:"8 Min.",level:"Mittel",color:"berry",emoji:"🍓",note:"Erdbeere · Cold Foam · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan möglich","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","4 reife Erdbeeren","1 TL Ahornsirup","150 ml Haferdrink","2 EL kalte Hafer-Sahne (für den Cold Foam)","Eiswürfel"],steps:["Erdbeeren mit Ahornsirup fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Haferdrink ins Glas füllen, dann den Matcha darübergeben.","Die kalte Hafer-Sahne aufschäumen und als Cold Foam oben auflegen."],description:"Erdbeerpüree, Matcha und ein luftig-kalter Cold Foam – fruchtig, samtig und erfrischend.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:11,title:"Mango Iced Matcha",category:"Iced",time:"7 Min.",level:"Einfach",color:"peach",emoji:"🥭",note:"Mango · Kokos · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt","Erfrischend"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","80 g reife Mango","1 TL Agavendicksaft","180 ml Kokosdrink","Eiswürfel"],steps:["Mango mit Agavendicksaft fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Kokosdrink ins Glas füllen.","Matcha langsam über den Kokosdrink gießen und servieren."],description:"Sonnige Mango auf cremigem Kokos mit sattem Matcha – ein tropischer Iced Genuss.",servings:"1 Glas",allergens:["Kokos"],draft:false},
  {id:12,title:"Honey Oat Matcha",category:"Iced",time:"5 Min.",level:"Einfach",color:"vanilla",emoji:"✿",note:"Honig · Hafer · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","200 ml Haferdrink","1 EL Honig","1/2 TL Zimt (optional)","Eiswürfel"],steps:["Honig im warmen Haferdrink verrühren, bis er sich gelöst hat.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Honig-Hafermilch hineingießen.","Matcha darübergeben, leicht umrühren und servieren."],description:"Warmer Honig in cremigem Hafer, gekrönt mit Matcha – ein klassisch wohliger Iced Latte.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:13,title:"Sparkling Lemon Matcha",category:"Iced",time:"5 Min.",level:"Einfach",color:"coconut",emoji:"◌",note:"Zitrone · Soda · Matcha",sweet:"Wenig",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Erfrischend"],ingredients:["1 TL Matcha-Pulver","50 ml heißes Wasser (ca. 80 °C)","150 ml Sodawasser","2 EL frischer Zitronensaft","1 TL Agavendicksaft","Eiswürfel"],steps:["Zitronensaft und Agavendicksaft in ein Glas geben und verrühren.","Matcha sieben, mit heißem Wasser glatt rühren.","Eis und Sodawasser ins Glas füllen.","Matcha über einen Löffel auf das Glas gießen, leicht umrühren und servieren."],description:"Prickelndes Soda mit frischer Zitrone und Matcha – der spritzige Klassiker für heiße Tage.",servings:"1 Glas",allergens:[],draft:false},
  {id:14,title:"Lavender Iced Matcha",category:"Iced",time:"7 Min.",level:"Einfach",color:"blueberry",emoji:"✾",note:"Lavendel · Vanille · Milch",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","180 ml Milch","1 TL Lavendelsirup","1/2 TL Vanilleextrakt","Eiswürfel"],steps:["Milch mit Lavendelsirup und Vanilleextrakt verrühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Lavendelmilch hineingießen.","Matcha darübergeben, kurz umrühren und servieren."],description:"Zarter Lavendel und Vanille auf eiskaltem Matcha – blumig, beruhigend und elegant.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:15,title:"Dirty Iced Matcha",category:"Iced",time:"6 Min.",level:"Einfach",color:"pistachio",emoji:"◒",note:"Espresso · Milch · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 doppelter Espresso (ca. 40 ml)","150 ml Milch","1 TL Ahornsirup","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Einen doppelten Espresso ziehen und kurz abkühlen lassen.","Ein Glas mit Eis füllen und die Milch mit dem Ahornsirup hineingießen.","Espresso und Matcha getrennt über die Milch gießen, sodass ein Latte-Effekt entsteht.","Kurz umrühren und servieren."],description:"Die gewagte Kombi aus Espresso und Matcha – kräftig, cremig und doppelt koffeinhaltig.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:16,title:"Pistachio Cream Matcha",category:"Cremig",time:"8 Min.",level:"Mittel",color:"pistachio",emoji:"◒",note:"Pistazie · Mandel · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 EL Pistaziencreme","180 ml Milch","1/2 TL Vanilleextrakt","1 TL Ahornsirup","Eiswürfel"],steps:["Pistaziencreme mit etwas Milch zu einer glatten Paste rühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Pistazienpaste, restliche Milch und Ahornsirup hineingeben.","Matcha darübergeben, kurz umrühren und servieren."],description:"Nussige Pistaziencreme auf sattem Matcha – süß, cremig und wunderbar grün.",servings:"1 Glas",allergens:["Milch / Laktose","Pistazie"],draft:false},
  {id:17,title:"White Chocolate Matcha",category:"Cremig",time:"8 Min.",level:"Einfach",color:"vanilla",emoji:"◈",note:"Weiße Schokolade · Milch · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","30 g weiße Schokolade","180 ml Milch","1 Prise Vanille","Eiswürfel"],steps:["Die weiße Schokolade grob hacken und in der warmen Milch unter Rühren schmelzen.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Schokomilch hineingießen.","Matcha langsam darübergeben und servieren."],description:"Zartschmelzende weiße Schokolade trifft auf Matcha – süßer Genuss für Schokoladenfans.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:18,title:"Biscoff Cloud Matcha",category:"Cremig",time:"8 Min.",level:"Mittel",color:"peach",emoji:"✦",note:"Karamellkeks · Cream Foam · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 EL Lotus-Biscoff-Creme","180 ml Milch","1/2 TL Zimt","2 EL Sahne (für den Cream Foam)","Eiswürfel"],steps:["Die Biscoff-Creme mit etwas Milch verrühren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und restliche Milch ins Glas füllen, Matcha darübergeben.","Die Sahne steif schlagen und als Cloud auf den Drink setzen."],description:"Karamellige Biscoff-Creme mit einer Sahnewolke und Matcha – dekadent und unwiderstehlich.",servings:"1 Glas",allergens:["Milch / Laktose","Gluten (Keks)"],draft:false},
  {id:19,title:"Coconut Cream Matcha",category:"Cremig",time:"7 Min.",level:"Einfach",color:"coconut",emoji:"🥥",note:"Kokoscreme · Vanille · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","160 ml Kokosdrink","40 ml Kokoscreme","1/2 TL Vanilleextrakt","1 TL Agavendicksaft","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Kokosdrink, Kokoscreme, Vanilleextrakt und Agavendicksaft verrühren.","Ein Glas mit Eis füllen und die Kokoscreme-Milch hineingießen.","Matcha darübergeben und servieren."],description:"Samtige Kokoscreme mit Vanille auf Matcha – tropisch-cremig und rein pflanzlich.",servings:"1 Glas",allergens:["Kokos"],draft:false},
  {id:20,title:"Crème Brûlée Matcha",category:"Cremig",time:"9 Min.",level:"Mittel",color:"vanilla",emoji:"◒",note:"Vanille · Karamell · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 EL Karamellsirup","180 ml Milch","1/2 TL Vanilleextrakt","1 Prise Zucker für das Topping","Eiswürfel"],steps:["Milch mit Vanilleextrakt und Karamellsirup verrühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Karamellmilch hineingießen.","Matcha darübergeben. Wer mag, karamellisiert etwas Zucker als Topping über dem Drink."],description:"Karamelliger Vanillegeschmack wie bei Crème Brûlée – auf eiskaltem Matcha serviert.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:21,title:"Strawberry Cheesecake Matcha",category:"Cremig",time:"10 Min.",level:"Mittel",color:"berry",emoji:"🍓",note:"Erdbeere · Frischkäse · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","4 Erdbeeren","1 EL Frischkäse (Doppelrahmstufe)","180 ml Milch","1 TL Ahornsirup","3 zerbröselte Butterkekse","Eiswürfel"],steps:["Erdbeeren mit Ahornsirup fein pürieren und in ein Glas geben.","Frischkäse mit der Milch glatt rühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Frischkäse-Milch ins Glas füllen, Matcha darübergeben.","Zum Schluss die Butterkeksbrösel darüberstreuen."],description:"Erdbeere, cremiger Frischkäse und Keksbrösel – ein Matcha, der nach Cheesecake schmeckt.",servings:"1 Glas",allergens:["Milch / Laktose","Gluten (Keks)"],draft:false},
  {id:22,title:"Banana Bread Matcha",category:"Cremig",time:"8 Min.",level:"Einfach",color:"peach",emoji:"🍌",note:"Banane · Zimt · Hafer",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1/2 reife Banane","1 TL Ahornsirup","1/2 TL Zimt","180 ml Hafermilch","Eiswürfel"],steps:["Banane mit Ahornsirup und Zimt fein pürieren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Bananenpüree und Hafermilch hineingeben.","Matcha darübergeben, kurz umrühren und servieren."],description:"Reife Banane mit Zimt auf Hafermilch-Matcha – wie frisch gebackenes Bananenbrot.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:23,title:"Almond Croissant Matcha",category:"Cremig",time:"8 Min.",level:"Einfach",color:"vanilla",emoji:"◐",note:"Mandel · Vanille · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","180 ml Mandeldrink","1/2 TL Vanilleextrakt","1 TL Ahornsirup","1 Prise Zimt","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Mandeldrink mit Vanilleextrakt, Ahornsirup und Zimt verrühren.","Ein Glas mit Eis füllen und die Mandelmilch hineingießen.","Matcha darübergeben, kurz umrühren und servieren."],description:"Sahniger Mandeldrink mit Vanille und einem Hauch Zimt – wie ein Buttercroissant, nur als Matcha.",servings:"1 Glas",allergens:["Nüsse (Mandel)"],draft:false},
  {id:24,title:"Black Sesame Matcha",category:"Cremig",time:"8 Min.",level:"Mittel",color:"blueberry",emoji:"●",note:"Schwarzer Sesam · Milch · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 EL schwarze Sesampaste (Tahini)","180 ml Milch","1 TL Agavendicksaft","1 Prise Salz","Eiswürfel"],steps:["Sesampaste mit etwas Milch zu einer glatten Masse rühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Sesampaste, restliche Milch und Agavendicksaft hineingeben.","Matcha darübergeben, vorsichtig umrühren und servieren."],description:"Nussige schwarze Sesampaste auf eiskaltem Matcha – geröstet, cremig und markant.",servings:"1 Glas",allergens:["Milch / Laktose","Sesam"],draft:false},
  {id:25,title:"Raspberry Vanilla Matcha",category:"Fruchtig",time:"8 Min.",level:"Einfach",color:"berry",emoji:"♥",note:"Himbeere · Vanille · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","50 g Himbeeren","180 ml Hafermilch","1/2 TL Vanilleextrakt","1 TL Ahornsirup","Eiswürfel"],steps:["Himbeeren mit etwas Hafermilch fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis, restliche Hafermilch, Vanilleextrakt und Ahornsirup ins Glas füllen.","Matcha darübergeben, leicht umrühren und servieren."],description:"Säuerliche Himbeeren mit Vanille auf cremigem Matcha – fruchtig, rosé und erfrischend.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:26,title:"Mango Coconut Matcha",category:"Fruchtig",time:"7 Min.",level:"Einfach",color:"peach",emoji:"🥭",note:"Mango · Kokos · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","80 g reife Mango","160 ml Kokosdrink","1 TL Agavendicksaft","1 Spritzer Limettensaft","Eiswürfel"],steps:["Mango mit Limettensaft fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Kokosdrink mit Agavendicksaft ins Glas füllen.","Matcha langsam über den Kokosdrink gießen und servieren."],description:"Süße Mango auf Kokos mit Matcha – tropisch-fruchtig, als würde Sommer im Glas stecken.",servings:"1 Glas",allergens:["Kokos"],draft:false},
  {id:27,title:"Yuzu Honey Matcha",category:"Fruchtig",time:"6 Min.",level:"Einfach",color:"coconut",emoji:"◌",note:"Yuzu · Honig · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 EL Yuzu-Saft","1 TL Honig","150 ml Sodawasser","Eiswürfel"],steps:["Yuzu-Saft und Honig in einem Glas verrühren, bis sich der Honig löst.","Matcha sieben, mit heißem Wasser glatt rühren.","Eis und Sodawasser ins Glas füllen.","Matcha über einen Löffel auf das Glas gießen, leicht umrühren und servieren."],description:"Zitrusfrische von Yuzu trifft süßen Honig und prickelndes Soda – ein spritziger Matcha.",servings:"1 Glas",allergens:[],draft:false},
  {id:28,title:"Passionfruit Matcha",category:"Fruchtig",time:"7 Min.",level:"Einfach",color:"peach",emoji:"◉",note:"Maracuja · Limette · Matcha",sweet:"Süß",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt","Erfrischend"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","2 Maracujas","1 TL Agavendicksaft","1 Spritzer Limettensaft","150 ml Kokosdrink","Eiswürfel"],steps:["Das Fruchtfleisch der Maracujas herauslösen und mit Agavendicksaft und Limettensaft verrühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Kokosdrink in ein Glas füllen, die Maracuja-Masse hineingeben.","Matcha darübergeben und servieren."],description:"Exotische Maracuja mit Limette und Kokos auf Matcha – fruchtig-exotisch und herrlich spritzig.",servings:"1 Glas",allergens:["Kokos"],draft:false},
  {id:29,title:"Cherry Blossom Matcha",category:"Fruchtig",time:"8 Min.",level:"Mittel",color:"berry",emoji:"🍒",note:"Kirsche · Mandel · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","6 Kirschen (entsteint)","180 ml Mandeldrink","1/2 TL Vanilleextrakt","1 TL Ahornsirup","Eiswürfel"],steps:["Kirschen mit etwas Mandeldrink fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis, restlichen Mandeldrink, Vanilleextrakt und Ahornsirup ins Glas füllen.","Matcha darübergeben, kurz umrühren und servieren."],description:"Süße Kirschen mit Mandel und Vanille auf Matcha – zart wie Blütenblätter im Frühling.",servings:"1 Glas",allergens:["Nüsse (Mandel)"],draft:false},
  {id:30,title:"Banana Matcha Latte",category:"Fruchtig",time:"7 Min.",level:"Einfach",color:"vanilla",emoji:"🍌",note:"Banane · Hafer · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1/2 reife Banane","180 ml Hafermilch","1/2 TL Zimt","1 TL Ahornsirup","Eiswürfel"],steps:["Banane mit Hafermilch, Zimt und Ahornsirup fein pürieren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Bananen-Hafermilch hineingießen.","Matcha darübergeben, leicht umrühren und servieren."],description:"Cremige Banane mit Zimt auf Hafermilch-Matcha – ein samtiger Latte wie vom Frühstückstisch.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:31,title:"Blackberry Mint Matcha",category:"Fruchtig",time:"8 Min.",level:"Einfach",color:"blueberry",emoji:"✿",note:"Brombeere · Minze · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt","Erfrischend"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","60 g Brombeeren","6 Minzblätter","180 ml Hafermilch","1 TL Agavendicksaft","Eiswürfel"],steps:["Brombeeren mit den Minzblättern fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Hafermilch mit Agavendicksaft ins Glas füllen.","Matcha darübergeben, leicht umrühren und servieren."],description:"Beerenfrische mit Minze auf cremigem Hafermilch-Matcha – kühl, fruchtig und wunderbar belebend.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:32,title:"Protein Vanilla Matcha",category:"Wellness",time:"6 Min.",level:"Einfach",color:"vanilla",emoji:"✦",note:"Vanilleprotein · Milch · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 Messlöffel Vanilleproteinpulver","200 ml Milch","1/2 TL Vanilleextrakt","Eiswürfel"],steps:["Proteinpulver mit der Milch kräftig aufschäumen oder mixen.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Proteinmilch hineingießen.","Matcha darübergeben, kurz umrühren und servieren."],description:"Der Fitness-Favorit: Vanilleprotein und Matcha für einen cremigen Eiweiß-Kick nach dem Training.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:33,title:"Chia Matcha Latte",category:"Wellness",time:"8 Min.",level:"Einfach",color:"coconut",emoji:"⌁",note:"Chia · Hafer · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 EL Chiasamen","200 ml Haferdrink","1 TL Ahornsirup","Eiswürfel"],steps:["Chiasamen mit etwas Haferdrink verrühren und ca. 5 Minuten quellen lassen.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Chiamasse, restlichen Haferdrink und Ahornsirup hineingeben.","Matcha darübergeben und servieren."],description:"Quellende Chiasamen auf cremigem Haferdrink-Matcha – der sättigende Wellness-Drink für zwischendurch.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:34,title:"Banana Oat Matcha Smoothie",category:"Wellness",time:"7 Min.",level:"Einfach",color:"peach",emoji:"🍌",note:"Banane · Hafer · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1 reife Banane","2 EL Haferflocken","200 ml Hafermilch","1 TL Ahornsirup"],steps:["Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Banane, Haferflocken, Hafermilch und Ahornsirup in einen Mixer geben.","Den Smoothie cremig mixen und in ein Glas füllen.","Den Matcha darübergeben, leicht verrühren und sofort trinken."],description:"Banane und Haferflocken als sämiger Smoothie mit Matcha – der schnelle Power-Start in den Tag.",servings:"1 Glas",allergens:["Gluten (Haferdrink)","Hafer"],draft:false},
  {id:35,title:"Coconut Water Matcha",category:"Wellness",time:"4 Min.",level:"Einfach",color:"coconut",emoji:"🥥",note:"Kokoswasser · Limette · Matcha",sweet:"Wenig",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Erfrischend"],ingredients:["1 TL Matcha-Pulver","50 ml heißes Wasser (ca. 80 °C)","200 ml Kokoswasser","1 Spritzer Limettensaft","Eiswürfel"],steps:["Matcha sieben, mit heißem Wasser glatt rühren.","Ein Glas mit Eiswürfeln füllen und das Kokoswasser hineingießen.","Limettensaft dazugeben.","Matcha über einen Löffel auf das Glas gießen, leicht umrühren und servieren."],description:"Leichtes Kokoswasser mit Limette und Matcha – der ultra-erfrischende, kalorienarme Durstlöscher.",servings:"1 Glas",allergens:["Kokos"],draft:false},
  {id:36,title:"Ginger Lemon Matcha",category:"Wellness",time:"5 Min.",level:"Einfach",color:"pistachio",emoji:"◌",note:"Ingwer · Zitrone · Matcha",sweet:"Wenig",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Erfrischend"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","2 EL frischer Zitronensaft","1 kleines Stück Ingwer (ca. 1 cm)","1 TL Agavendicksaft","150 ml Sodawasser","Eiswürfel"],steps:["Ingwer fein reiben und mit Zitronensaft und Agavendicksaft in ein Glas geben.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Eis und Sodawasser ins Glas füllen.","Matcha darübergießen, kurz umrühren und servieren."],description:"Scharfer Ingwer, frische Zitrone und prickelndes Soda – der belebende Wellness-Matcha mit Kick.",servings:"1 Glas",allergens:[],draft:false},
  {id:37,title:"Date Cinnamon Matcha",category:"Wellness",time:"7 Min.",level:"Einfach",color:"vanilla",emoji:"✦",note:"Dattel · Zimt · Milch",sweet:"Süß",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","2 entsteinte Datteln","180 ml Milch","1/2 TL Zimt","1 Prise Vanille","Eiswürfel"],steps:["Datteln mit der Milch fein pürieren und mit Zimt und Vanille verrühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen und die Dattelmilch hineingießen.","Matcha darübergeben, leicht umrühren und servieren."],description:"Natürliche Süße von Datteln mit Zimt auf cremiger Milch-Matcha – karamellig, warm und wohlig.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:38,title:"Golden Oat Matcha",category:"Wellness",time:"8 Min.",level:"Einfach",color:"peach",emoji:"☀",note:"Hafer · Kurkuma · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","1/2 TL Kurkuma","1 Prise schwarzer Pfeffer","200 ml Hafermilch","1 TL Ahornsirup","Eiswürfel"],steps:["Kurkuma und Pfeffer mit etwas Hafermilch glatt rühren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Kurkumamischung, restliche Hafermilch und Ahornsirup hineingeben.","Matcha darübergeben und servieren."],description:"Kurkuma und Matcha im Doppelpack auf cremigem Hafer – goldgelb, wärmend und voller guter Zutaten.",servings:"1 Glas",allergens:["Gluten (Haferdrink)"],draft:false},
  {id:39,title:"Blueberry Yogurt Matcha",category:"Wellness",time:"8 Min.",level:"Mittel",color:"blueberry",emoji:"🫐",note:"Joghurt · Blaubeere · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Nein",tags:["Vegetarisch","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","50 g Blaubeeren","2 EL griechischer Joghurt","180 ml Milch","1 TL Ahornsirup","Eiswürfel"],steps:["Blaubeeren mit Joghurt und Ahornsirup fein pürieren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Blaubeer-Joghurt und Milch hineingeben.","Matcha darübergeben, vorsichtig umrühren und servieren."],description:"Cremiger Joghurt mit Blaubeeren auf Matcha – samtig, leicht säuerlich und richtig erfrischend.",servings:"1 Glas",allergens:["Milch / Laktose"],draft:false},
  {id:40,title:"Mint Cucumber Matcha",category:"Wellness",time:"6 Min.",level:"Einfach",color:"coconut",emoji:"⌁",note:"Gurke · Minze · Limette",sweet:"Wenig",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Erfrischend"],ingredients:["1 TL Matcha-Pulver","50 ml heißes Wasser (ca. 80 °C)","1/4 Gurke","6 Minzblätter","1 Spritzer Limettensaft","200 ml Sodawasser","Eiswürfel"],steps:["Gurke und Minzblätter fein pürieren und in ein Glas geben.","Matcha sieben, mit heißem Wasser glatt rühren.","Eis, Limettensaft und Sodawasser ins Glas füllen.","Matcha über einen Löffel auf das Glas gießen, leicht umrühren und servieren."],description:"Kühle Gurke mit Minze und Limette auf prickelndem Matcha – der Wellness-Drink für heiße Tage.",servings:"1 Glas",allergens:[],draft:false},
  {id:41,title:"Tahini Date Matcha",category:"Wellness",time:"7 Min.",level:"Mittel",color:"pistachio",emoji:"◐",note:"Tahini · Dattel · Matcha",sweet:"Mittel",temperature:"Kalt",vegan:"Ja",tags:["Vegan","Kalt"],ingredients:["1 TL Matcha-Pulver","60 ml heißes Wasser (ca. 80 °C)","2 entsteinte Datteln","1 EL Tahini (Sesampaste)","180 ml Mandeldrink","Eiswürfel"],steps:["Datteln mit Tahini und etwas Mandeldrink fein pürieren.","Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.","Ein Glas mit Eis füllen, Dattel-Tahini-Mischung und restlichen Mandeldrink hineingeben.","Matcha darübergeben, kurz umrühren und servieren."],description:"Sesamige Tahini und süße Datteln auf Matcha – nussig-karamellig und wunderbar cremig.",servings:"1 Glas",allergens:["Nüsse (Mandel)","Sesam"],draft:false}
];
const deriveMeta = (r) => {
  const sweet = r.sweet || (/Biscoff|Brûlée|Cheesecake|White Chocolate|Banana Bread/.test(r.title) ? "Süß" : /Classic|Sparkling|Ginger|Cucumber/.test(r.title) ? "Wenig" : "Mittel");
  const temperature = r.temperature || (r.category === "Iced" || r.category === "Fruchtig" || r.category === "Wellness" ? "Kalt" : "Heiß oder kalt");
  const vegan = r.vegan || (/Vanilla Cream|White Chocolate|Biscoff|Brûlée|Cheesecake/.test(r.title) ? "Nein" : "Ja");
  const level = r.level || (/Cold Foam|Crème|Cheesecake|Sesame|Croissant|Tonic|Pistachio|Golden/.test(r.title) ? "Mittel" : "Einfach");
  return { sweet, temperature, vegan, level };
};
const infoPills = (r) => {
  const info = deriveMeta(r);
  return `<div class="recipe-meta"><span>◷ ${r.time}</span><span>◈ ${info.level}</span><span>◌ ${info.sweet}</span><span>◉ ${info.temperature}</span><span>♧ Vegan: ${info.vegan}</span></div>`;
};
const draftIngredients = (r, info) => {
  const items = ["1 TL Matcha-Pulver", "60 ml heißes Wasser (ca. 80 °C)", "180 ml Milch oder pflanzlicher Drink", `Die Zutaten für: ${r.note}`];
  if (info.temperature === "Kalt") items.push("Eiswürfel");
  return items;
};
const draftSteps = (r, info) => {
  const cold = info.temperature === "Kalt";
  return [
    "Die geschmacksgebenden Zutaten vorbereiten und nach Wunsch fein pürieren oder verrühren.",
    "Matcha sieben, mit heißem Wasser anrühren und schaumig schlagen.",
    cold ? "Ein Glas mit Eis und Milch füllen." : "Milch erwärmen oder aufschäumen.",
    "Matcha langsam dazugeben, vorsichtig umrühren und direkt servieren."
  ];
};
const normalizeText = (s) => String(s == null ? "" : s).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
const searchRecipes = (list, query) => {
  const terms = normalizeText(query).split(/\s+/).filter(Boolean);
  if (!terms.length) return list;
  return list.filter((r) => {
    const haystack = normalizeText([r.title, r.note, r.category, deriveMeta(r).level, r.time, ...(r.tags || []), ...(r.ingredients || []), ...(r.steps || [])].join(" "));
    return terms.every((t) => haystack.includes(t));
  });
};
const savedRecipes = () => JSON.parse(localStorage.getItem("matchly-saved") || "[]");
const toggleSaved = (id) => {
  const list = savedRecipes();
  const next = list.includes(id) ? list.filter((i) => i !== id) : [...list, id];
  localStorage.setItem("matchly-saved", JSON.stringify(next));
  return next;
};
const checkedIngredients = (id) => (JSON.parse(localStorage.getItem("matchly-checked") || "{}")[id] || []);
const toggleChecked = (id, idx) => {
  const all = JSON.parse(localStorage.getItem("matchly-checked") || "{}");
  const list = all[id] || [];
  all[id] = list.includes(idx) ? list.filter((i) => i !== idx) : [...list, idx];
  localStorage.setItem("matchly-checked", JSON.stringify(all));
  return all[id];
};
const checkedSteps = (id) => (JSON.parse(localStorage.getItem("matchly-steps") || "{}")[id] || []);
const toggleStep = (id, idx) => {
  const all = JSON.parse(localStorage.getItem("matchly-steps") || "{}");
  const list = all[id] || [];
  all[id] = list.includes(idx) ? list.filter((i) => i !== idx) : [...list, idx];
  localStorage.setItem("matchly-steps", JSON.stringify(all));
  return all[id];
};
const similarRecipes = (r, n = 3) => RECIPES.filter((x) => x.category === r.category && x.id !== r.id).slice(0, n);
const detailMetaHTML = (r) => {
  const meta = deriveMeta(r);
  return `<div class="recipe-meta"><span>◷ ${r.time}</span><span>◈ ${meta.level}</span><span>◌ ${meta.sweet}</span><span>◉ ${meta.temperature}</span><span>♧ Vegan: ${meta.vegan}</span><span>◑ ${r.servings || "1 Glas"}</span></div>`;
};
const recipeDetailHTML = (r) => {
  const meta = deriveMeta(r);
  const isSaved = savedRecipes().includes(r.id);
  const description = r.description || r.note;
  const tagsHTML = r.draft ? "" : `<div class="detail-tags">${r.tags.map((t) => `<span>${t}</span>`).join("")}</div>`;
  const allergensHTML = (r.allergens && r.allergens.length) ? `<div class="detail-allergens"><strong>Allergene</strong>${r.allergens.map((a) => `<span>${a}</span>`).join("")}</div>` : "";
  const similar = similarRecipes(r);
  const similarHTML = similar.length ? `<section class="similar-recipes"><h3>Ähnliche Rezepte</h3><div class="similar-grid">${similar.map((s) => `<button class="similar-card ${s.color}" data-detail-open="${s.id}" aria-label="${s.title} öffnen"><span class="similar-emoji">${s.emoji}</span><strong>${s.title}</strong><small>◷ ${s.time} · ${s.category}</small></button>`).join("")}</div></section>` : "";
  const ingredients = r.draft ? draftIngredients(r, meta) : r.ingredients;
  const steps = r.draft ? draftSteps(r, meta) : r.steps;
  const checked = checkedIngredients(r.id);
  const stepsChecked = checkedSteps(r.id);
  return `<div class="detail-hero ${r.color}"><span>${r.emoji}</span></div><div class="detail-body"><div class="detail-top"><div><p class="eyebrow">${r.category.toUpperCase()}${r.draft ? " · REZEPTENTWURF" : ""}</p><h2>${r.title}</h2></div><div class="detail-actions"><button class="detail-share" data-share-id="${r.id}" aria-label="${r.title} teilen">↗</button><button class="detail-heart ${isSaved ? "is-saved" : ""}" data-id="${r.id}" aria-label="${r.title} speichern">${isSaved ? "♥" : "♡"}</button></div></div><p class="detail-description">${description}</p>${detailMetaHTML(r)}${tagsHTML}<div class="detail-grid"><section><h3>Zutaten <small>für ${r.servings || "1 Glas"}</small></h3><ul>${ingredients.map((ing, idx) => `<li class="check-item${checked.includes(idx) ? " is-checked" : ""}"><label><input type="checkbox" data-recipe-id="${r.id}" data-check-idx="${idx}"${checked.includes(idx) ? " checked" : ""}><span>${ing}</span></label></li>`).join("")}</ul>${allergensHTML}</section><section><h3>Zubereitung <small class="step-progress">${stepsChecked.length}/${steps.length} Schritte</small></h3><ol>${steps.map((s, idx) => `<li class="step-item${stepsChecked.includes(idx) ? " is-checked" : ""}"><label><input type="checkbox" data-recipe-id="${r.id}" data-step-idx="${idx}"${stepsChecked.includes(idx) ? " checked" : ""}><span>${s}</span></label></li>`).join("")}</ol></section></div>${similarHTML}<p class="allergy-note">${r.draft ? "Testentwurf: Mengen und Schritte vor der Veröffentlichung bitte selbst testen und gegebenenfalls anpassen." : "Hinweis: Prüfe bei pflanzlichen Drinks, Sirupen und Toppings immer die Zutatenliste, besonders bei Allergien."}</p></div>`;
};
const showCopyToast = () => {
  let toast = document.querySelector(".share-toast");
  if (!toast) {
    toast = document.createElement("div");
    toast.className = "share-toast";
    document.body.appendChild(toast);
  }
  toast.textContent = "✓ Link in die Zwischenablage kopiert";
  toast.classList.add("show");
  clearTimeout(showCopyToast._t);
  showCopyToast._t = setTimeout(() => toast.classList.remove("show"), 1800);
};
const shareRecipe = async (r) => {
  const url = `${location.origin}${location.pathname}#rezept-${r.id}`;
  if (navigator.share) {
    try { await navigator.share({ title: "Matchly", text: `${r.title} · ${r.note}`, url }); return; } catch (err) {}
  }
  try { await navigator.clipboard.writeText(url); showCopyToast(); } catch (err) {}
};
